### ISSUE TITLE
small items caught when reviewing code

### ISSUE THREAD

**Issue by steve-h** [vapor/core#129]
Byte+Control.swift line 93 :
`public static let tilda: Byte = 0x7E`
  should be spelled `tilde` not `tilda`
your call whether an @available renamed is needed with fix.

Also line 108:
`public static let pipe: UInt8 = 0x7C` should be
`public static let pipe: Byte = 0x7C`

**Comment by tanner0101** [comment]
@steve-h would love a PR to fix this one. Deprecate + fixit for rename would be awesome 👍
