### ISSUE TITLE
deprecate Async

### ISSUE THREAD

**Issue by tanner0101** [vapor/core#132]
A goal for version 4 of this package is to move all helpers in the `Async` module upstream and remove the dependency on Swift NIO here. The reasoning is:

- Core should be a lightweight package that all of Vapor's packages rely on (including NIO makes that quite heavy). 
- Vapor should minimize the amount of API on top of NIO to make the ecosystem feel more cohesive.

This will obviously be quite a big breaking change, so this is open to discussion!

**Comment by rafiki270** [comment]
Weren’t you rather excited about an apple team actually doing a lot of the heavy lifting so Vapor team can focus on features? I understand your reasoning then and here above too both makes sense, just not sure why would you give up that extra nio resource tbh

**Comment by tanner0101** [comment]
@rafiki270 the `Async` module is left over from before NIO existed. I'd rather rely on NIO's libraries without needing to maintain this left over stuff (now mostly just convenience and aliases) in the middle.

**Comment by rafiki270** [comment]
Oh :) It did sound to me like you want to remove the whole NIO and do our own implementation again :)))

**Comment by MrLotU** [comment]
@tanner0101 I think we can close this since `Core` will be deprecated with Vapor 4
