### ISSUE TITLE
Data does not conform to ReflectionDecodable

### ISSUE THREAD

**Issue by andrewtheis** [vapor/core#135]
**Steps**
1. Create a new Vapor 3 project w/PostgreSQLFluent
2. Create a `PostgreSQLModel` subclass with a `Data` property
3. Add model to migration config in configure.swift
4. Run application

**Expected Result**
Migration for your new model runs and creates a `bytea` PostgeSQL column

**Actual Result**
Error is thrown: `⚠️ [CoreError.ReflectionDecodable: `Data` does not conform to `ReflectionDecodable`.]`

**Comment by tanner0101** [comment]
Thanks for reporting that one @andrewtheis!
