### ISSUE TITLE
Possible bug in Async.flatten

### ISSUE THREAD

**Issue by MrMage** [vapor/core#136]
According to https://github.com/vapor/core/blob/master/Sources/Async/Future%2BFlatten.swift, "the order of the results will match the order of the futures in the input array.". But the current implementation simply adds an awaiter to each future, which appends its result to the final result array. That means that elements actually get appended in the order in which the futures are fulfilled, not in the order the futures had in the input array.

**Comment by tanner0101** [comment]
That is a bug, thank you for finding that @MrMage. We used to have an `orderedFlatten` and non ordered `flatten`. It looks like the docs for `orderedFlatten` got applied here incorrectly. I think the best solution here is to make this actually do an ordered flatten.
