### ISSUE TITLE
Does Core support Cocoapods?

### ISSUE THREAD

**Issue by agisilaos** [vapor/core#165]
Hello, 👋 I was just thinking if Core is supported by Cocoapods? Atm, I have the 2.0.1 version installed and I have some issues since this version isn't updated to Swift 4.0.1. As I checked in the PR's the PR regarding the newest version of Swift is already merged but the pod's version isn't updated just yet. 🤔

**Comment by rafiki270** [comment]
Hi, are you sure you meant cocoapods?

**Comment by agisilaos** [comment]
Yep, currently I have Core installed through Cocoapods.

**Comment by agisilaos** [comment]
@rafiki270 I updated the title of the issue to make more sense.

**Comment by calebkleveter** [comment]
Core had CoocoaPod support in version 2, but it hasn't been added in 3. A PR would be welcome though!

**Comment by agisilaos** [comment]
@calebkleveter What's the best way to do that? Since I'm not the owner of the repo etc. I would love to open a PR, I just need a bit of help.

**Comment by joscdk** [comment]
@agisilaos you can fork the Repo, and make the changes in your fork, and then make a PR from your fork into this repo :)

**Comment by agisilaos** [comment]
@joscdk Hm, not meant it in that way. More of like: How I'm gonna do it since it's an already created project, what I'm gonna add in the dependencies part of the podspec and if I add the dependencies which version I'm gonna add as well? That kind of stuff.

**Comment by calebkleveter** [comment]
Good point. I'm not sure that will work at this point because NIO doesn't support CocoaPods. Might be worth looking into.

**Comment by MrLotU** [comment]
Nope, right now Core does not have cocoapods support, and with the deprecation of Core with Vapor 4, I don't see adding support high on the priorities list 😄
