### ISSUE TITLE
Date of RFC1123 can't fit to real date format

### ISSUE THREAD

**Issue by atjason** [vapor/core#25]
For this class: core/Sources/Core/RFC1123.swift
https://github.com/vapor/core/blob/5f4049900be7eacf4de43aa1240f4eb101c2edb6/Sources/Core/RFC1123.swift

The date format is "EEE',' dd MMM yyyy HH':'mm':'ss 'GMT'".

But in fact, the real date string may be: "Thu, 01-Jan-1970 00:00:01 GMT". For this case, the expires date will be nil.

So, it's better to fit to more corresponding date format.

**Comment by loganwright** [comment]
maybe falling back to 850 as done here is the right move

https://github.com/cyclestreets/ios/blob/master/lib/categories/NSDate%2BNSDateRFC1123.m

This could be a good starter task for someone looking to contribute 👍

**Comment by BrettRToomey** [comment]
@LoganWright do you know if this has been picked up or not?

**Comment by tanner0101** [comment]
We've changed how we do RFC1123 quite a bit since this. Should be fixed now.
