### ISSUE TITLE
Foundation Base64 encoding broken on Swift 3.1

### ISSUE THREAD

**Issue by vzsg** [vapor/core#41]
The latest stable version 1.1.1 uses Foundation's Base64 encoding, which is broken in the 3.1 release, causing low-level crashes in JWT (already worked around), websockets (vapor/vapor#970) and possibly other places.

**Comment by vzsg** [comment]
Hmm. I'm trying to reproduce the same crash in a unit test, but haven't succeeded yet. I'll reopen this later.

**Comment by vzsg** [comment]
Still not a test-based reproduction, but vapor/vapor#970 is the same issue.

For JWT, I have [backported](https://github.com/vapor/jwt/blob/vapor-1/Sources/JWT/Encodings/Base64Encoder.swift) Core 2's implementation, so perhaps it could be moved here for a new Core 1 patch version?

**Comment by tanner0101** [comment]
That would probably be a good idea. Who knows what other code is susceptible to this crash now.

**Comment by vzsg** [comment]
The mentioned issue is now confirmed to be resolved, so I'm closing this.
